[program:uwsgi]
command=uwsgi --ini /opt/apps/uwsgi.ini --daemonize /var/log/uwsgi.log --pidfile /tmp/project-master.pid
autostart=true
autorestart=true
startretries=3
numprocs=1
stopwaitsecs=10
stopsignal=INT
redirect_stderr=true
