# Generated by Django 4.2.13 on 2024-12-08 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='testers',
            field=models.ManyToManyField(blank=True, db_index=True, help_text='Feature Testers', related_name='feature_testers', to=settings.AUTH_USER_MODEL, verbose_name='testers'),
        ),
    ]
