services:
  db:
    image:    mysql:8.0
    restart:  always
    volumes:
      - mysql-db:/var/lib/mysql
      - ./docker_config/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      MYSQL_DATABASE:       toremember
      MYSQL_ROOT_PASSWORD:  root
    ports:
      - 3306:3306
    expose:
      - 3306
    healthcheck:
        test:     ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout:  10s
        retries:  10

  redis:
    image:    redis:alpine
    command:  redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./docker_config/redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: "exit 0"
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  web:
    build:
      dockerfile: Dockerfile-slim
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - redis
    env_file:
      - ./docker_config/docker-compose/dev.env
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    working_dir: /app/src
    healthcheck:
      test:         ["CMD", "/curl", "127.0.0.1:8000/api/status"]
      interval:     30s
      timeout:      2s
      retries:      3
      start_period: 1s

  # swagger:
  #   image: swaggerapi/swagger-ui
  #   environment:
  #     SWAGGER_JSON: /swagger/swagger.yml
  #   volumes:
  #     - ./swagger:/swagger
  #   ports:
  #     - 8081:8080

volumes:
  mysql-db:
    driver: local
