# Generated by Django 4.2.13 on 2024-05-11 23:49

import blog.models.Blog
import ckeditor_uploader.fields
import ddcore.models.Comment
import ddcore.models.Rating
import ddcore.models.View
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from="title",
                        verbose_name="slug",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(upload_to=blog.models.Blog.blog_directory_path),
                ),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True,
                        help_text="Post Content",
                        null=True,
                        verbose_name="Content",
                    ),
                ),
                (
                    "hashtag",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Hashtag",
                        max_length=80,
                        null=True,
                        verbose_name="Hashtag",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("0", "Draft"), ("1", "Visible"), ("2", "Closed")],
                        default="0",
                        help_text="Post Status",
                        max_length=2,
                        verbose_name="Status",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Post Author",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Post Author",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated List of Tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "blog post",
                "verbose_name_plural": "blog posts",
                "ordering": ["-created"],
            },
            bases=(
                models.Model,
                ddcore.models.CommentMixin,
                ddcore.models.RatingMixin,
                ddcore.models.ViewMixin,
            ),
        ),
    ]
