# Generated by Django 4.2.13 on 2025-03-01 16:13

import collection.models.Collection
import ddcore.Serializers
import ddcore.models.Comment
import ddcore.models.Complaint
import ddcore.models.Rating
import ddcore.models.View
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import meta.models
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('privateurl', '0001_initial'),
        ('events', '0004_alter_participation_role'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug')),
                ('custom_data', models.JSONField(blank=True, encoder=ddcore.Serializers.JSONEncoder, null=True, verbose_name='Custom Data')),
                ('is_hidden', models.BooleanField(default=False, help_text='Is Object hidden?', verbose_name='Is hidden?')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is Object deleted?', verbose_name='Is deleted?')),
                ('deleted', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='deleted')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('preview', models.ImageField(blank=True, upload_to=collection.models.collection_preview_directory_path)),
                ('cover', models.ImageField(blank=True, upload_to=collection.models.collection_cover_directory_path)),
                ('hashtag', models.CharField(blank=True, db_index=True, help_text='Hashtag', max_length=80, null=True, verbose_name='Hashtag')),
                ('visibility', models.CharField(choices=[('0', 'Public'), ('1', 'Private')], default='0', help_text='Collection Visibility', max_length=2, verbose_name='Visibility')),
                ('allow_comments', models.BooleanField(default=True, help_text='I would like to allow Comments', verbose_name='I would like to allow Comments')),
                ('is_newly_created', models.BooleanField(default=True)),
                ('author', models.ForeignKey(help_text='Collection Author', on_delete=django.db.models.deletion.CASCADE, related_name='posted_collections', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('created_by', models.ForeignKey(blank=True, help_text='User, created the Object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User, deleted the Object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_deleted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('events', models.ManyToManyField(blank=True, db_index=True, help_text='Collection Events', related_name='collection_events', to='events.event', verbose_name='Events')),
                ('followers', models.ManyToManyField(blank=True, db_index=True, help_text='Collection Followers', related_name='collection_followers', to=settings.AUTH_USER_MODEL, verbose_name='Followers')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User, modified the Object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_modified_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('private_url', models.ForeignKey(blank=True, help_text='Collection private URL', null=True, on_delete=django.db.models.deletion.SET_NULL, to='privateurl.privateurl', verbose_name='Private URL')),
                ('subscribers', models.ManyToManyField(blank=True, db_index=True, help_text='Collection Subscribers', related_name='collection_subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Subscribers')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated List of Tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
                'ordering': ['-created'],
            },
            bases=(meta.models.ModelMeta, models.Model, ddcore.models.CommentMixin, ddcore.models.ComplaintMixin, ddcore.models.RatingMixin, ddcore.models.ViewMixin),
        ),
    ]
