# Generated by Django 4.2.13 on 2025-07-22 22:41

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('0', 'Draft'), ('1', 'Published'), ('2', 'Closed')], default='0', help_text='Collection Status', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A Comma-separated List of Tags.<br/>If you plan to add only one Tag, that consists of multiple Words, it is recommended to wrap the Tag in Quotes, e.g. "<b><i>This is multi-word Tag"</i></b>.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
