# Generated by Django 4.2.13 on 2025-01-03 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Section Author', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_faq_sections', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
