# Generated by Django 4.2.13 on 2024-07-14 12:06

import accounts.models.UserProfile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover',
            field=models.ImageField(blank=True, upload_to=accounts.models.user_cover_directory_path),
        ),
    ]
