# Generated by Django 4.2.13 on 2025-01-03 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddcore', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.ForeignKey(blank=True, help_text='User Address', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddcore.address', verbose_name='Address'),
        ),
    ]
