# Generated by Django 4.2.13 on 2024-12-11 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('privateurl', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='private_url',
            field=models.ForeignKey(blank=True, help_text='Event private URL', null=True, on_delete=django.db.models.deletion.CASCADE, to='privateurl.privateurl', verbose_name='Private URL'),
        ),
    ]
