# Generated by Django 4.2.13 on 2024-08-08 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_category_custom_data_event_custom_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='followers',
            field=models.ManyToManyField(blank=True, db_index=True, help_text='Event Followers', related_name='event_followers', to=settings.AUTH_USER_MODEL, verbose_name='Followers'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='private_url',
            field=models.URLField(blank=True, help_text='Event private URL', max_length=255, null=True, verbose_name='Private URL'),
        ),
        migrations.AddField(
            model_name='event',
            name='subscribers',
            field=models.ManyToManyField(blank=True, db_index=True, help_text='Event Subscribers', related_name='event_subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Subscribers'),
        ),
    ]
