# Generated by Django 4.2.13 on 2024-12-11 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('privateurl', '0001_initial'),
        ('ddcore', '0001_initial'),
        ('organizations', '0001_initial'),
        ('events', '0002_alter_event_private_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Event Location', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddcore.address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Event Organization', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='event',
            name='private_url',
            field=models.ForeignKey(blank=True, help_text='Event private URL', null=True, on_delete=django.db.models.deletion.SET_NULL, to='privateurl.privateurl', verbose_name='Private URL'),
        ),
    ]
