# Generated by Django 4.2.13 on 2025-01-03 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_address_alter_event_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Role, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_participations', to='events.role', verbose_name='Role'),
        ),
    ]
