# Generated by Django 4.2.13 on 2024-07-25 17:46

import ddcore.Serializers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='custom_data',
            field=models.JSONField(blank=True, encoder=ddcore.Serializers.JSONEncoder, null=True, verbose_name='Custom Data'),
        ),
        migrations.AddField(
            model_name='organizationgroup',
            name='custom_data',
            field=models.JSONField(blank=True, encoder=ddcore.Serializers.JSONEncoder, null=True, verbose_name='Custom Data'),
        ),
        migrations.AddField(
            model_name='organizationstaff',
            name='custom_data',
            field=models.JSONField(blank=True, encoder=ddcore.Serializers.JSONEncoder, null=True, verbose_name='Custom Data'),
        ),
    ]
