# Generated by Django 4.2.13 on 2025-01-03 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddcore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Organization Address', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddcore.address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Organization Author', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='organizationgroup',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Organization Group Author', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_group_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='organizationstaff',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Organization Staff Member Author', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_staff_members_created', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
