# Generated by Django 4.2.13 on 2024-08-08 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_organization_custom_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='followers',
            field=models.ManyToManyField(blank=True, db_index=True, help_text='Organization Followers', related_name='organization_followers', to=settings.AUTH_USER_MODEL, verbose_name='Followers'),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscribers',
            field=models.ManyToManyField(blank=True, db_index=True, help_text='Organization Subscribers', related_name='organization_subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Subscribers'),
        ),
    ]
